name: hotel_booking
description: Hotel booking app with in-app payements.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  built_value:
  dio: 
  envied: 
  flutter:
    sdk: flutter
  flutter_form_builder: 
  flutter_native_splash: 
  form_builder_extra_fields: 
  form_builder_validators:
  supabase_flutter:
  get: 
  google_fonts: 
  google_nav_bar: 
  intl: 
  json_annotation: 
  retrofit: 
  flutter_svg: 
  internet_connection_checker: 
  shared_preferences: 
  liquid_swipe: 
  smooth_page_indicator: 
  firebase_core: 
  firebase_auth:
  cloud_firestore:
  flutter_udid:
  country_picker:
  pinput:
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.2.3
  scroll_to_hide: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 
  envied_generator: 
  build_runner: 
  built_value_generator: 
  json_serializable: 
  retrofit_generator: 

flutter_native_splash:
  color:  "#003554"
  color_dark: "#003554"
  image:  assets/images/logo.jpg
  image_dark: assets/images/logo.jpg
  web:  false
  android_12: 
    image:  assets/images/logo.jpg
    image_dark: assets/images/logo.jpg
    icon_background_color:  "#003554"
    icon_background_color_dark: "#003554"


flutter:
  uses-material-design: true
  assets:
    - assets/text/terms_conditions.txt
    - assets/google_fonts/
    - assets/images/
    - assets/onboarding/
    - assets/auth/