name: hotel_booking
description: Hotel booking app with in-app payements.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  built_value: ^8.6.1
  dio: ^5.3.2
  envied: ^0.3.0+3
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.1.0
  flutter_native_splash: ^2.3.1
  form_builder_extra_fields: ^10.0.0
  form_builder_validators: ^9.0.0
  get: ^4.6.5
  google_fonts: ^5.1.0
  google_nav_bar: ^5.0.6
  intl: ^0.18.0
  json_annotation: ^4.8.1
  retrofit: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  envied_generator: ^0.3.0+3
  build_runner: ^2.4.6
  built_value_generator: ^8.6.1
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8

flutter_native_splash:
  color:  "#003554"
  color_dark: "#003554"
  image:  assets/images/logo.jpg
  image_dark: assets/images/logo.jpg
  web:  false
  android_12: 
    image:  assets/images/logo.jpg
    image_dark: assets/images/logo.jpg
    icon_background_color:  "#003554"
    icon_background_color_dark: "#003554"


flutter:
  uses-material-design: true
  assets:
    - assets/text/terms_conditions.txt
    - assets/google_fonts/
    - assets/images/